### ISSUE TITLE
The installation is too silent

### ISSUE THREAD

**Issue by bbossola** [MeterianHQ/docker-scanner-engine#5]
The installation is too silent and does not give any feedback to the end user. We know that the main reason is docker-compose, which now blurps output all over the place, but cannot we do something in the middle? Maybe installing some key packages manually before launching docker-compose and providing the user with some feedback?

**Comment by n-insaidoo** [comment]
The installation substantially takes care of pulling all the images relative to the services in our `Composefiles` at once. It could be structured to pull these (silently) one by one giving feedback after each completion (we could even prioritise pulling lighter images first to have some initial feedback sooner). 
I think this will improve it overall, how does this approach sound to you? @bbossola

**Comment by bbossola** [comment]
Yes, that was my thought exactly
